import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { 
  faBarChart, faCalendar, faChain, faClock, faCloud, faComment, faEnvelope, faHome, faHeart, 
  faCog, faPen, faTrash, faDroplet, faCode, faUser, faBug, faSmile 
} from '@fortawesome/free-solid-svg-icons';

import { 
  faFacebook, faTwitter, faInstagram, faGithub, faReact, faLinkedin, faWordpress, 
  faApple, faDocker, faAmazon 
} from '@fortawesome/free-brands-svg-icons';

const icons = [
  { 
    name: 'Facebook', 
    icon: faFacebook, 
    category: 'brand',
    subCategory: 'social',
    style: 'Light',
    featured: 'Sponsored',
  },
  { 
    name: 'Twitter', 
    icon: faTwitter, 
    category: 'brand',
    subCategory: 'social',
    style: 'Light',
    featured: 'Sponsored',
  },
  { 
    name: 'Instagram', 
    icon: faInstagram, 
    category: 'brand',
    subCategory: 'social',
    style: 'Light',
    featured: 'Sponsored',
  },
  { 
    name: 'Github', 
    icon: faGithub, 
    category: 'brand',
    subCategory: 'component',
    style: 'Light',
    featured: 'Sponsored',
  },
  { 
    name: 'React', 
    icon: faReact, 
    category: 'brand',
    subCategory: 'learning',
    style: 'Light',
    featured: 'Sponsored',
  },
  { 
    name: 'User', 
    icon: faUser, 
    category: 'free',
    subCategory: 'user',
    style: 'Thin',
    featured: 'Favorite',
  },
  { 
    name: 'Apple', 
    icon: faApple, 
    category: 'free',
    subCategory: 'shop',
    style: 'Thin',
    featured: 'Favorite',
  },
  { 
    name: 'Pen', 
    icon: faPen, 
    category: 'free',
    subCategory: 'user',
    style: 'Thin',
    featured: 'Favorite',
  },
  { 
    name: 'Cog', 
    icon: faCog, 
    category: 'sharp',
    subCategory: 'component',
    style: 'Regular',
    featured: 'new',
  },
  { 
    name: 'Heart', 
    icon: faHeart, 
    category: 'sharp',
    subCategory: 'component',
    style: 'Regular',
    featured: 'new',
  },
  { 
    name: 'Amazon', 
    icon: faAmazon, 
    category: 'sharp',
    subCategory: 'shop',
    style: 'Regular',
    featured: 'new',
  },
  { 
    name: 'Home', 
    icon: faHome, 
    category: 'sharp',
    subCategory: 'home',
    style: 'Regular',
    featured: 'new',
  },
  { 
    name: 'Calendar', 
    icon: faCalendar, 
    category: 'classic',
    subCategory: 'component',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Clock', 
    icon: faClock, 
    category: 'classic',
    subCategory: 'component',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Cloud', 
    icon: faCloud, 
    category: 'classic',
    subCategory: 'Weather',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Smile', 
    icon: faSmile, 
    category: 'free',
    subCategory: 'Emoji',
    style: 'Thin',
    featured: 'Favorite',
  },
  { 
    name: 'Docker', 
    icon: faDocker, 
    category: 'free',
    subCategory: 'learning',
    style: 'Thin',
    featured: 'Favorite',
  },
  { 
    name: 'Chain', 
    icon: faChain, 
    category: 'classic',
    subCategory: 'component',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Trash', 
    icon: faTrash, 
    category: 'sharp',
    subCategory: 'component',
    style: 'Regular',
    featured: 'new',
  },
  { 
    name: 'Wordpress', 
    icon: faWordpress, 
    category: 'classic',
    subCategory: 'learning',
    style: 'Regular',
    featured: 'new',
  },
  { 
    name: 'BarChart', 
    icon: faBarChart, 
    category: 'sharp',
    subCategory: 'component',
    style: 'Solid',
    featured: 'new',
  },
];

export default icons;
