import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { 
  faBarChart, faCalendar, faChain, faClock, faCloud, faComment, faEnvelope, faHome, faHeart, 
  faCog, faPen, faTrash, faDroplet, faCode, faUser, faBug 
} from '@fortawesome/free-solid-svg-icons';

import { 
  faFacebook, faTwitter, faInstagram, faGithub, faReact, faLinkedin, faWordpress, 
  faApple, faDocker, faAmazon 
} from '@fortawesome/free-brands-svg-icons';

const icons = [
  { 
    name: 'Facebook', 
    icon: faFacebook, 
    category: 'brand',
    subCategory: 'F',
    style: 'Light',
    featured: 'Sponsored',
  },
  { 
    name: 'Twitter', 
    icon: faTwitter, 
    category: 'brand',
    subCategory: 'T',
    style: 'Light',
    featured: 'Sponsored',
  },
  { 
    name: 'Instagram', 
    icon: faInstagram, 
    category: 'brand',
    subCategory: 'I',
    style: 'Light',
    featured: 'Sponsored',
  },
  { 
    name: 'Github', 
    icon: faGithub, 
    category: 'brand',
    subCategory: 'G',
    style: 'Light',
    featured: 'Sponsored',
  },
  { 
    name: 'React', 
    icon: faReact, 
    category: 'brand',
    subCategory: 'R',
    style: 'Light',
    featured: 'Sponsored',
  },
  { 
    name: 'User', 
    icon: faUser, 
    category: 'free',
    subCategory: 'U',
    style: 'Solid',
    featured: 'Favorite',
  },
  { 
    name: 'Apple', 
    icon: faApple, 
    category: 'free',
    subCategory: 'A',
    style: 'Regular',
    featured: 'Favorite',
  },
  { 
    name: 'Pen', 
    icon: faPen, 
    category: 'free',
    subCategory: 'P',
    style: 'Regular',
    featured: 'Favorite',
  },
  { 
    name: 'Cog', 
    icon: faCog, 
    category: 'sharp',
    subCategory: 'C',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Heart', 
    icon: faHeart, 
    category: 'sharp',
    subCategory: 'H',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Amazon', 
    icon: faAmazon, 
    category: 'sharp',
    subCategory: 'A',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Home', 
    icon: faHome, 
    category: 'sharp',
    subCategory: 'H',
    style: 'Regular',
    featured: 'new',
  },
  { 
    name: 'Calendar', 
    icon: faCalendar, 
    category: 'classic',
    subCategory: 'C',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Clock', 
    icon: faClock, 
    category: 'classic',
    subCategory: 'C',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Cloud', 
    icon: faCloud, 
    category: 'classic',
    subCategory: 'C',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Bug', 
    icon: faBug, 
    category: 'free',
    subCategory: 'B',
    style: 'Regular',
    featured: 'Favorite',
  },
  { 
    name: 'Docker', 
    icon: faDocker, 
    category: 'free',
    subCategory: 'D',
    style: 'Regular',
    featured: 'Favorite',
  },
  { 
    name: 'Chain', 
    icon: faChain, 
    category: 'classic',
    subCategory: 'C',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Trash', 
    icon: faTrash, 
    category: 'sharp',
    subCategory: 'T',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'Wordpress', 
    icon: faWordpress, 
    category: 'classic',
    subCategory: 'W',
    style: 'Solid',
    featured: 'new',
  },
  { 
    name: 'BarChart', 
    icon: faBarChart, 
    category: 'sharp',
    subCategory: 'B',
    style: 'Solid',
    featured: 'new',
  },
];

export default icons;
